name       : lirc
version    : 0.10.1
release    : 8
source     :
    - https://netcologne.dl.sourceforge.net/project/lirc/LIRC/0.10.1/lirc-0.10.1.tar.bz2 : 8b753c60df2a7f5dcda2db72c38e448ca300c3b4f6000c1501fcb0bd5df414f2
license    : GPL-2.0-or-later
component  : system.utils
summary    : Linux Infrared Remote Control utilities
description: |
    LIRC is a package that supports receiving and sending IR signals
    of IR remote controls, adding functionality and flexibility to the basic
    support in the Linux kernel.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libftdi1)
    - pkgconfig(libusb)
    - pkgconfig(portaudiocpp)
    - pkgconfig(python3)
    - pkgconfig(x11)
environment: |
    unset LD_AS_NEEDED
setup      : |
    sed -i -e 's|/usr/local/etc/|/etc/|' contrib/irman2lirc

    %configure --disable-static \
               --with-lockdir=/var/lock/lockdev
build      : |
    %make
install    : |
    %make_install

    install -Dm 00644 $pkgfiles/lirc.tmpfiles $installdir%libdir%/tmpfiles.d/lirc.conf
    install -Dm 00644 $pkgfiles/lirc.sysusers $installdir%libdir%/sysusers.d/lirc.conf
    install -Dm 00644 contrib/60-lirc.rules $installdir%libdir%/udev/rules.d/60-lirc.rules
    install -Dm 00644 contrib/99-remote-control-lirc.rules $installdir%libdir%/udev/rules.d/99-remote-control-lirc.rules

    rm -rf $installdir/var/run
