name       : lirc
version    : 0.9.4d
release    : 2
source     :
    - https://netcologne.dl.sourceforge.net/project/lirc/LIRC/0.9.4d/lirc-0.9.4d.tar.bz2 : c68f18c35b489b865c0a741d119b136e8702191538cd3551b977a7af6c4e41ab
license    : GPL-2.0
component  : system.utils
summary    : Linux Infrared Remote Control utilities
description: |
    LIRC is a package that supports receiving and sending IR signals
    of IR remote controls, adding functionality and flexibility to the basic
    support in the Linux kernel.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libftdi1)
    - pkgconfig(libusb)
    - pkgconfig(portaudiocpp)
    - pkgconfig(python3)
    - pkgconfig(x11)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    install -Dm644 $pkgfiles/lirc.tmpfiles $installdir%libdir%/tmpfiles.d/lirc.conf
